service: contact-form

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  app:
    handler: handler.app
    events:
        - http: https://lhnkfl6hy1.execute-api.us-east-1.amazonaws.com/dev
        - http: https://lhnkfl6hy1.execute-api.us-east-1.amazonaws.com/dev/{proxy+}
          method: post
          path: contact-form
          cors: true
